spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/GetJob
#    username: root
#    password: honesty1234!
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  thymeleaf:
    enabled: false


### Swagger ###
springdoc:
  packages-to-scan: com.example.GetJobV100.controller  # 컨트롤러 가져오기
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /api-docs/
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: method









